from tkinter import Tk, Button, Frame, messagebox, Label, Entry

ventana = Tk()
ventana.title("Tareas")
ventana.geometry("600x400")
seccion1 = Frame(ventana, bg = "#B8FFAB")
seccion1.pack(expand=True, fill="both")
bienvenida = Label(seccion1, text="Registro de Tareas", bg="#B8FFAB", font="consolas 20 bold")
bienvenida.pack()
seccion2 = Frame(ventana, bg= "#D8B769")
seccion2.pack(expand=True, fill="both")
Nombre = Label(seccion1, text="Nombre de la tarea:", font="Arial 12", bg="#B8FFAB")
Nombre.place(x=190, y=60)
NoT = Label(seccion1, text="No. de la tarea:", font="Arial 12", bg="#B8FFAB")
NoT.place(x=200, y=90)
Descripcion = Label(seccion1, text="Descripción:", font="Arial 12", bg="#B8FFAB")
Descripcion.place(x="200", y="115")
FI = Label(seccion1, text="Fecha de inicio:", font="Arial 12", bg="#B8FFAB")
FI.place(x="200", y="135")
FF = Label(seccion1, text="Fecha de fin:", font="Arial 12", bg="#B8FFAB")
FF.place(x="200", y="160")
nombre2 = Entry(seccion1)
nombre2.place(x=340, y=65)
NoT2 = Entry(seccion1)
NoT2.place(x=340, y=90)
Descripcion2 = Entry(seccion1)
Descripcion2.place(x=340, y=115)
FI2 = Entry(seccion1)
FI2.place(x=340, y=140)
FF2 = Entry(seccion1)
FF2.place(x=340, y=165)

botonRegistrar = Button(seccion2, text="Guardar", fg="black", bg="#D8B769", font="Arial 12")
botonRegistrar.place(x=260, y=60)

ventana.mainloop()